name: Run Postman API Tests with Newman

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch
  workflow_dispatch:  # Enable manual trigger through GitHub API/UI

jobs:
  newman-test:
    runs-on: ubuntu-latest  # Or another runner you are using

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection with Newman
        run: |
          newman run postman/AuthService.postman_collection.json -e postman/uat.postman_environment.json
